### ISSUE TITLE
Everything is escaped.

### ISSUE THREAD

**Issue by skx** [zupzup/markdown-code-highlight-go#1]
Using this sample everything output is escaped.

For example my output looks like this:

      ...
      ...
     <body>
        &lt;p&gt;Hello&lt;/p&gt;
        &lt;p&gt;Some Go Code:&lt;/p&gt;
     ...

To fix this I had to change:

    err = t.Execute(os.Stdout, struct{ Content string }{Content: replaced})

To:

     err = t.Execute(os.Stdout, struct{ Content template.HTML }{Content: template.HTML(replaced)})

**Comment by zupzup** [comment]
oh, right. thx for the tip. I'll change it once I'm back home :)
